import os
import tempfile
import subprocess
import platform

# Determine executable path based on OS
sys_plat = platform.system()
exe_name = "realesrgan-ncnn-vulkan.exe" if sys_plat == "Windows" else "realesrgan-ncnn-vulkan"
EXE_PATH = os.path.join(os.path.dirname(__file__), "realesrgan_ncnn", exe_name)

def enhance_image_local(file_bytes: bytes) -> bytes:
    """
    Core AI enhancement pipeline running locally via ncnn-vulkan executable.
    This completely bypasses heavy PyTorch requirements and runs incredibly fast
    using your local GPU (via Vulkan) or CPU.
    """
    if not os.path.exists(EXE_PATH):
        # Fallback to cv2 cubic resize if executable isn't downloaded yet
        import cv2
        import numpy as np
        print("Warning: RealESRGAN executable not found. Falling back to simple resize.")
        nparr = np.frombuffer(file_bytes, np.uint8)
        img = cv2.imdecode(nparr, cv2.IMREAD_UNCHANGED)
        height, width = img.shape[:2]
        output = cv2.resize(img, (width * 4, height * 4), interpolation=cv2.INTER_CUBIC)
        is_success, buffer = cv2.imencode(".png", output)
        return buffer.tobytes()

    with tempfile.TemporaryDirectory() as temp_dir:
        input_path = os.path.join(temp_dir, "input.png")
        output_path = os.path.join(temp_dir, "output.png")
        
        with open(input_path, "wb") as f:
            f.write(file_bytes)
            
        # Run RealESRGAN ncnn
        # -i input path
        # -o output path
        # -n realesrgan-x4plus (default high-quality model included in the download)
        # -s 4 (scale factor)
        cmd = [EXE_PATH, "-i", input_path, "-o", output_path, "-s", "4"]
        
        try:
            # We don't use check=True immediately so we can read stderr if it fails
            result = subprocess.run(cmd, capture_output=True, text=True)
            if result.returncode != 0:
                raise RuntimeError(f"RealESRGAN failed: {result.stderr}")
        except Exception as e:
            raise RuntimeError(f"Execution failed: {str(e)}")
            
        if not os.path.exists(output_path):
            raise RuntimeError("Output file was not generated by RealESRGAN")
            
        with open(output_path, "rb") as f:
            return f.read()
